spring:
  application:
    name: album
  
  datasource:
    # L'host 'album-db' viene usato quando il DB gira in un container separato [cite: 1541, 1550]
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/album_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update # Crea le tabelle automaticamente se non esistono
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Usa JSON per l'interscambio di messaggi [cite: 1208-1210]
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery: 
        instanceId: ${spring.application.name}-${spring.cloud.client.hostname}-${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s
        healthCheckCriticalTimeout: 45s
        queryPassing: true 

asw:
  kafka:
    channel:
      [cite_start]out: album-service-event-channel # Il topic per gli eventi [cite: 999]

  kafka:
    bootstrap-servers: "localhost:9092"
    #potrebbe essere kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server: 
  port: ${PORT:${SERVER_PORT:0}}
#  port: 8080
  # per swagger, se dietro a un api gateway 
  forward-headers-strategy: framework

# fa il logging dei comandi sql eseguiti 
#spring.jpa.show-sql: true
# disable OSIV
spring.jpa.open-in-view: false

#asw.kafka.channel.out=album-created-topic
# Configura anche i serializer per inviare oggetti JSON [cite: 1208-1210]
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
