name: bettermusic

services:
  consul:
    container_name: bettermusic-consul
    image: docker.io/hashicorp/consul:latest
    ports:
      - "8500:8500"
    environment:
      - CONSUL_HOST=bettermusic-consul
    networks:
      - service-network


networks:
  service-network:
    driver: bridge
    name: bettermusic_service-network
