include 'album'
include 'album-api'
include 'album-api-event'
include 'bettermusic-common-api-event'
include 'connessioni'
include 'connessioni-api'
include 'connessioni-api-event'
include 'recensioni'
include 'recensioni-api'
include 'recensioni-api-event'
include 'recensioni-seguite'
include 'recensioni-seguite-api'
include 'api-gateway'

rootProject.name = 'asw-bettermusic'