######################################################
# Dockerfile per connessioni 
######################################################

FROM eclipse-temurin:21-jdk 

ADD build/libs/recensioni-seguite.jar recensioni-seguite.jar

EXPOSE 8080

ENTRYPOINT ["java", "-Xms64m", "-Xmx128m", "-jar", "recensioni-seguite.jar"]


