######################################################
# Dockerfile per connessioni 
######################################################

FROM eclipse-temurin:21-jdk 

ADD build/libs/connessioni.jar connessioni.jar

EXPOSE 8080

ENTRYPOINT ["java", "-Xms64m", "-Xmx128m", "-jar", "connessioni.jar"]


