services:
  connessioni-database:
    image: postgres:16
    container_name: connessioni-db
    environment:
      POSTGRES_DB: connessioni_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - db-network

networks:
  db-network:
    driver: bridge