######################################################
# Dockerfile per connessioni 
######################################################

FROM eclipse-temurin:21-jdk 

ADD build/libs/recensioni.jar recensioni.jar

EXPOSE 8080

ENTRYPOINT ["java", "-Xms64m", "-Xmx128m", "-jar", "recensioni.jar"]


