services:
  recensioni-database:
    image: postgres:16
    container_name: recensioni-db
    environment:
      POSTGRES_DB: recensioni_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - db-network

networks:
  db-network:
    driver: bridge